#!/usr/bin/perl
#=======================
# Author : Ali Moradzade
# Created: 2022/02/03
#=======================
use warnings;
use v5.10;
use utf8;
use autodie;

#automatic convert

sub convert_to_java_method {
	my $procedure_name = shift(@_);
	(my $method_name = $procedure_name) =~ s/_(\w)/\U$1/g;
	my @arguments = @_;

	my @method_arguments = @arguments;
	$_ = "String " . $_ foreach (@method_arguments);

	my @format;
	push @format, "'%s'" foreach (1..@arguments);

	print "public static void $method_name(", (join ',', @method_arguments), ")\n";
	printf "{
		String parameters = String.format(
				\"(%s)\",
				%s);
		String query = \"call $procedure_name(parameters)\";
}\n\n", (join ',', @format),(join ',', @arguments);
}

# Link: https://stackoverflow.com/questions/953707/in-perl-how-can-i-read-an-entire-file-into-a-string

foreach (@ARGV) {
	my $file = $_;
	my $document = do {
		local $/ = undef;
		open my $fh, "<", $file
			or die "could not open $file: $!";
		<$fh>;
	};

	my %name_argument = ($document =~ /
		create\s+procedure\s+
		(?<procedure_name>\w+)
		\(\n
			(?<arguments>.*?)
		^\)$
	/gmsix);

	foreach $value (values %name_argument) {
		$value =~ s/^\s+//gm;
		$value =~ s/\s+$//m;
		$value =~ s/\n//g;
	}
	foreach $value (values %name_argument) {
		$value =~ s/
			[A-Z]+
			(?:\(\d*\))?
			,?
		//gx;
	}
	while (($k, $v) = each %name_argument) {
		$v =~ s/_param//g;
		$v =~ s/_(\w)/\U$1/g;

		&convert_to_java_method($k, (split ' ', $v));
	}
}
